version: '3'

services:
  db:
    container_name: abc-db
    image: postgres:latest
    environment: 
      - POSTGRES_DB=abc
      - POSTGRES_USER=abc
      - POSTGRES_PASSWORD=abc
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data

  web:
    container_name: 'abc-project'
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
     - "8000:8000"
    depends_on:
      - db
volumes:
  database-data: