# Generated by Django 4.0 on 2022-08-02 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
